### ISSUE TITLE
How to Log user out

### ISSUE THREAD

**Issue by phavor** [championswimmer/vuex-persist#110]
Am using `vuex-persist` to persist user data on login.

I've tried implementing logout functionality, but I've noticed that when I log in as a different user, I still see the details of the previous user...

Any help would be appreciated.

**Comment by doublej42** [comment]
Sound like you are not updating your vuex state on logout.  Sounds like an issue with your code. Maybe post a detailed example to stackoverflow.

**Comment by carbontwelve** [comment]
@phavor On each of my stores I have a `RESET_STATE` mutation that gets executed by my logout process e.g:

```js
const defaultStateFactory = () => {
  return {
    draft: {},
    items: {}
  }
};

export const state = defaultStateFactory()

export const types = {
  RESET_USERS_STATE: 'RESET_USERS_STATE',
  SET_USERS: 'SET_USERS',
};

export const mutations = {
  [types.RESET_USERS_STATE] (state) {
    Object.assign(state, defaultStateFactory())
  },
  [types.SET_USERS] (state, payload) {
    // ...
  },
};

export const actions = {
  resetState ({ commit }) {
    commit(types.RESET_USERS_STATE)
  },
};
```

All my stores are loaded into VueX namespaced so on logout I can call `this.$store.dispatch('user.resetState');` and it seems the _vuex-persist_ plugin picks up those changes.

**Comment by tmladek** [comment]
@carbontwelve This is a good solution (and I am in fact doing the same), but I'm also wondering whether it would make sense to have a global `clearPersistence()` function that simply erases the entire storage?

**Comment by carbontwelve** [comment]
@tmladek Yes; that would actually be perfect. At the moment when I log out a user I have to jump through some hoops to disable vuex-persist and then delete the entry in local storage so no PI data is left. If the plugin provided a global clear function that would make things easier.

**Comment by tmladek** [comment]
I take it a `clearPersistence()` function is not to be implemented or considered, then?

**Comment by albernhagen** [comment]
@championswimmer is there a way we could do a `clearPersistsence()` as @tmladek mentioned?  I have a different use case -- I'm working in an application where I've sometimes had store properties later change to true getters (using your other vuex-module-decorators library).  This causes issues because when state is restored from local storage, it tries to assign an old property that is now a getter and my app is in an error state.  There's not an easy way to prevent that from happening, especially as more devs work on it.  I'd like to be able to wipe a clean slate in certain situations to remove that restriction.  Any guidance?

**Comment by dshastry** [comment]
+1 for a clearPersistence function. Have a similar use case.
