### ISSUE TITLE
'localforage' is not defined

### ISSUE THREAD

**Issue by ssuess** [championswimmer/vuex-persist#117]
I am unable to get localforage to work with the persist plugin. I have tried `window.localforage`, and `window.localForage`, but they seem to be the exact same as just using `window.localstorage` and will only store my values in localstorage (not IndexedDB where my localforage plugin stores things)

And trying to define storage as `localforage`, or `localForage` results in an error: `'localforage' is not defined`

I definitely have it installed and working (both the base package and vue-localforage) because if I call it from outside vuex-persist I am able to store into it with commands like:

`this.$setItem('lfstate', { item1: false, item2: false })`

Any tips on how to properly define this in my store's index.js file? my code currently looks like this:

````
import Vue from 'vue'
import Vuex from 'vuex'
import VuexPersist from 'vuex-persist'

import rstruth from './rstruth'

Vue.use(Vuex)

const vuexLocal = new VuexPersist({
  key: 'my-app',
  storage: localforage  //or window.localstorage, or localForage, etc
})

export default function () {
  const Store = new Vuex.Store({
    modules: {
      rstruth
    },
    plugins: [vuexLocal.plugin]
  })

  return Store
}
````

**Comment by ssuess** [comment]
UGH, I just figured out the problem. I needed to directly import localforage into my store's index.js file, even though it was being imported by my vue-localforage package in my main app index file. So, adding this line to the top of the code above:
````
import localforage from 'localforage'
````

Solved my problem, allowing me to just use `localforage` as my storage type and now making the items store in IndexedDB where all my other items are. Hope this helps someone else out.

**Comment by esti** [comment]
@ssuess one related question:

I had imported the localforage package as you say and I am referencing it in the storage section of VuexPersist configuration but, my data are still being saved in localStorage instead of indexedDB. Is it necessary to set any other configuration parameter for localForage to use indexedDB? As for their readme, I understand that is the default storage...

**Comment by ssuess** [comment]
@esti have you defined storage as your import name (`localforage` not `window.localforage` or anything else)?

**Comment by esti** [comment]
Yep!

<pre>
import {localForage} from 'localforage';
...
const vuexLocalStorage = new VuexPersistence({
  storage: localForage,
  ...
})
</pre>

**Comment by ssuess** [comment]
one other thing you might try is to set `asyncStorage: true`, I was not sure if it was necessary but did it because localforage uses promises...

**Comment by esti** [comment]
If I add that I get the following error in the javascript console:

<pre>
TypeError: storage.getItem(...).then is not a function
</pre>

**Comment by esti** [comment]
I found my mistake. Thought it would be handy to point it here in case someone gets the same error. The import of localforage should be without curly braces:

<pre>
import localForage from 'localforage';
</pre>

The reason is, apparently, because the module is exported as 'default' not as 'named module'. (I'm still not too familiarized with ES6 as to understand it completely).
