### ISSUE TITLE
Error - Unexpected token: name (MockStorage)

### ISSUE THREAD

**Issue by msbir** [championswimmer/vuex-persist#75]
Hey, having this error when run `npm run build` -

`ERROR in static/js/vendor.1d08fa61caa6133701c2.js from UglifyJs Unexpected token: name (MockStorage) [./node_modules/vuex-persist/dist/esm/index.js:6,0][static/js/vendor.1d08fa61caa6133701c2.js:32405,4]`

vuex-persist version - ^1.7.2
vue version - ^2.5.15
vuex version - ^2.5.0

Using this package with localForage storage (local forage version - ^1.7.2)

Thanks !

**Comment by championswimmer** [comment]
update to 1.8.0

**Comment by nasermirzaei89** [comment]
I have this problem with version 2.0.0

**Comment by msantore** [comment]
> I have this problem with version 2.0.0

Me too -

**Comment by chrisjbrown** [comment]
> I have this problem with version 2.0.0

same for me

can we re-open this?

**Comment by chrisjbrown** [comment]
Solved for me:

Seems vue-persist has es6 code that needs to be transpiled to es5 which if depending on the transpiler you're using as some versions of uglifyjsplugin don't support es6.

I am using webpack 3 with the built in webpack uglifyjsplugin. but that uses a really old version of uglify. My fix was updating to uglifyjsplugin 1.3 and using that instead of the built in 
`webpack.optimize.UglifyJsPlugin`

**Comment by championswimmer** [comment]
The readme has details about how to transpile if you're on Vue CLI 3

**Comment by connected** [comment]
Possible solution is to use UMD module def. instead.
`import VuexPersist from 'vuex-persist/dist/umd'`

**Comment by nicolauria** [comment]
connected's solution above worked for me. Thanks man!
