### ISSUE TITLE
How can I only persist specific key in a Vuex Module

### ISSUE THREAD

**Issue by aliraza371** [championswimmer/vuex-persist#99]
Hello, 

I have a question, How can I persist specific key in a module?: 

```
reducer: (state) => ({
    adminAccountType: state.RolesAndPermissionModule.adminAccountType,
  })
```

I only want to persist the "adminAccountType" object within RolesAndPermissionModule , but when I do that it creates the new key in root state with "adminAccountType"

Thanks

**Comment by championswimmer** [comment]
Reducer takes the state (in memory) as argument and returns the state (or
its part) to be saved into your persistence.

Return whatever you want to return from reducer. Keeps keys you want. Drop
keys you don't want.

**Comment by brooksca** [comment]
aliraza,

Not sure if you got an answer to this or not. Looks like it was closed pretty quickly. I was having this same problem fixed it by doing the following:

```js
// --- store/index.js

import Vue from 'vue'
import Vuex from 'vuex'
import VuexPersist from 'vuex-persist'

import persistedModuleName from './persistedModuleFile'

Vue.use(Vuex)
...

const vueLocalStorage = new VuexPersist({
  key: 'STORAGE_KEY',
  storage: window.localStorage,
  reducer: (state) => ({
    persistedModuleName: {
      CompanyName: state.persistedModuleName.CompanyName,
      CustomerId: state.persistedModuleName.CustomerId,
      SignedInUser: state.persistedModuleName.SignedInUser,
      SignedInUserRole: state.persistedModuleName.SignedInUserRole
    }
  })
})

export default new Vuex.Store({
  state: state,
  getters: getters,
  actions: actions,
  mutations: mutations,
  modules: {
    persistedModuleName
  },
  plugins: [vueLocalStorage.plugin]
})
```

Hope that helps.

**Comment by aliraza371** [comment]
> ```js
> CompanyName
> ```



> ```js
> n
> ```


Great, Thanks 

It really helps.

**Comment by chiky123ser** [comment]
> aliraza,
> 
> Not sure if you got an answer to this or not. Looks like it was closed pretty quickly. I was having this same problem fixed it by doing the following:
> 
> ```js
> // --- store/index.js
> 
> import Vue from 'vue'
> import Vuex from 'vuex'
> import VuexPersist from 'vuex-persist'
> 
> import persistedModuleName from './persistedModuleFile'
> 
> Vue.use(Vuex)
> ...
> 
> const vueLocalStorage = new VuexPersist({
>   key: 'STORAGE_KEY',
>   storage: window.localStorage,
>   reducer: (state) => ({
>     persistedModuleName: {
>       CompanyName: state.persistedModuleName.CompanyName,
>       CustomerId: state.persistedModuleName.CustomerId,
>       SignedInUser: state.persistedModuleName.SignedInUser,
>       SignedInUserRole: state.persistedModuleName.SignedInUserRole
>     }
>   })
> })
> 
> export default new Vuex.Store({
>   state: state,
>   getters: getters,
>   actions: actions,
>   mutations: mutations,
>   modules: {
>     persistedModuleName
>   },
>   plugins: [vueLocalStorage.plugin]
> })
> ```
> 
> Hope that helps.

I had the same problem, thank you very much

**Comment by vanessametonini** [comment]
Hi folks, sorry for reviving this thread. But I need a light to solve the problem of the types in the case of use reducer in a TypeScript app.

![Screen Shot 2020-10-14 at 18 32 08](https://user-images.githubusercontent.com/3089882/96047678-dee7c780-0e4b-11eb-9334-a1d479c9538e.png)
**compiling error**
![Screen Shot 2020-10-14 at 18 34 33](https://user-images.githubusercontent.com/3089882/96047744-f32bc480-0e4b-11eb-8be4-974007df2ed5.png)

My state on `localStorage` is already in the way I want because, in the end, it works, but in the terminal, the type errors still there.

One way is to use `any` instead of RootState in: `new VuexPersistence<RootState>`;

Another way is to declare my modules in the `RootState` type.
The type of my RootState is declare as:
```
export type RootState = {
  version: string;
}
```
and it needs to be like:
```
export type RootState = {
  version: string;
  auth: AuthState;
  signup: SignUpState,
  org: OrgState
}
```

I'm not sure if it's appropriate to do this second way...

thanks in advance
